name: Secure Deploy

on: [push]

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ✅ Replace this step with OIDC login
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: <e924e888-00fb-4df1-a64a-1650fb7aa753>        # from Azure AD app
        tenant-id: <17016688-2c7b-40cc-a62c-a9c20221bd56>           # Azure tenant ID
        subscription-id: <ce6ae346-d4fd-4aab-82d7-7db942b501d6> # Azure subscription ID
        auth-type: oidc                        # important for OIDC login

    - name: Terraform Init & Plan
      run: |
        terraform init
        terraform plan
