name: Secure Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Terraform (must be before any Terraform commands)
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest


    # 3️⃣ Azure login via OIDC
    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        client-id: e924e888-00fb-4df1-a64a-1650fb7aa753       # from Azure AD app
        tenant-id: 17016688-2c7b-40cc-a62c-a9c20221bd56          # Azure tenant ID
        subscription-id: ce6ae346-d4fd-4aab-82d7-7db942b501d6 # Azure subscription ID
        auth-type: oidc

    # 4️⃣ Terraform init & plan
    - name: Terraform Init & Plan
      run: |
        terraform init
        terraform plan

    # 5️⃣ Optional: Terraform apply
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
